version: '3.8'

services:
  orchestrator:
    build: ./orchestrator
    container_name: supos-orchestrator
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Docker socket for inspecting containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Orchestrator persistent config
      - orchestrator_config:/app/config
      
      # CRITICAL: Mount entire workspace (contains bin/, .env, docker-compose files)
      - .:/workspace
      
      # CRITICAL: Mount user's VOLUMES_PATH to same location as host
      # This makes install script see volumes at expected path
      - ${VOLUMES_PATH}:${VOLUMES_PATH}
    environment:
      - FLASK_ENV=production
      - SUPOS_WORKSPACE=/workspace
      # Pass VOLUMES_PATH to orchestrator for validation
      - VOLUMES_PATH=${VOLUMES_PATH}
    networks:
      - supos_orchestrator_network

networks:
  supos_orchestrator_network:
    name: supos_orchestrator_network
    driver: bridge

volumes:
  orchestrator_config:
    name: supos_orchestrator_config